import Head from 'next/head'
import { useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Link from 'next/link';

export default function Navbar() {
    const [logined, setLogined] = useState();

  
  
    // const handleSubmit = async (e) => {
    //   e.preventDefault();
    //   const res = await login_user(formData);
    //   if (res.success) {
    //     toast.success(res.message);
    //     Cookies.set("token", res.token);
    //     setTimeout(() => {
    //       Router.push("/home");
    //     }, 1000);
    //   } else {
    //     toast.error(res.message);
    //   }
    // };
  
    return (
      <>
        <Head>
          <title>Login System</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="bg-white-700 text-center text-indigo-600 h-16 flex justify-between items-center px-10">
            <img src="/cobbleweb.svg" alt="" />
            <div>
            <Link href="/login" className="font-medium text-indigo-600 dark:text-primary-500 mr-3">Log In</Link>
            <Link href="/register" className="font-medium text-indigo-600 dark:text-primary-500 ">Sign up</Link>
            </div>
        </section>
        <ToastContainer />
      </>
    )
  }